export const MM_RAG_UPLOAD_OPTIONS = `
## Two upload choices, both with real tradeoffs
- **Find visually similar figures (optional)**: off by default. Turning it on
  additionally encodes each figure/chart image with a small image-recognition
  model, adding a "find similar figures" button to figure citations. This
  does NOT change how chat questions are answered — captions always power
  that — it only adds a bonus visual-search feature. Downloads an extra model
  the first time it's used and adds a few seconds per figure during upload.
- **Sharing scope**: "Session only" (default) means only you can query what
  you uploaded, and it's gone if you refresh. "Share with all visitors right
  now" makes it queryable by anyone using the tool while this server keeps
  running — useful for showing a document to someone else in the same
  sitting. Neither option is permanent: this demo runs without persistent
  storage, so a server restart clears everything uploaded, shared or not.

## Re-uploading a document you already added
If you upload a file that looks like a newer version of something already
in this chat — same filename, or text that's highly similar even under a
different name — a banner asks you before doing anything: "Replace the old
one, or keep both?" Nothing is ever swapped out automatically. Choosing
"Replace old" removes the earlier version the same way the × button does;
"Keep both" just dismisses the banner and leaves both documents in the
chat. This only compares against documents still in your current session,
never anything from another chat.

## Answers keep working even if a provider is busy
Chat answers are generated by an AI provider (Groq, Gemini, Cohere, etc). If
your selected provider is rate-limited or briefly unavailable, the tool
automatically retries with another provider behind the scenes. This only
happens before an answer has started; if a provider fails partway through
writing a response, that's shown as an error rather than silently switched,
since splicing two providers' text together would produce a garbled answer.

A tag above the chat always shows which provider actually generated the
answer. Normally it just says "Answered via X." If your chosen provider
failed and a fallback stepped in, it says so plainly instead — e.g.
"cohere unavailable (rate limited) — answered via groq" — so a different
provider answering is never a silent surprise.

## Answer length
A "Concise / Normal / Detailed" toggle sits next to the Provider button.
"Concise" asks the AI for the shortest complete answer — 1-3 sentences,
no extra context — good for a quick fact check like "what's the invoice
total?" "Detailed" asks it to explain its reasoning and pull in related
details from the source, good for "walk me through how this pricing table
is structured." "Normal" (default) is unchanged from before this toggle
existed. It only changes how the SAME retrieved information is written up
— it doesn't change what's retrieved or which citations show.

Clicking a different length regenerates the answer you're currently
looking at, in place — you don't need to ask the question again. It
replaces just the last answer bubble; earlier answers in the conversation
keep whatever length they were originally given at.
`.trim();