"use client";

import { useEffect, useState } from "react";
import { DEMOS, type Demo } from "@/data/demos";
import HandbookDemo from "./HandbookDemo";

/**
 * Puts a "Watch this work" button under every chapter heading that has a demo.
 *
 * Done by reaching into the rendered Markdown rather than by putting the
 * button in the Markdown itself, because public/handbook.md is generated by
 * scripts/build-handbook.py from the same source as the printed book — and a
 * button is meaningless on paper. The heading ids it matches on are stable:
 * the build script writes them, and the contents page links to them.
 *
 * The buttons are built as plain DOM rather than portalled React nodes. That
 * looks like the lesser tool but it is the right one here: portals would need
 * the list of host elements in state, and filling that state from an effect is
 * a cascading render for something that never changes after the first paint.
 */
export default function DemoLauncher() {
  // setOpen from useState is stable for the life of the component, so the
  // listeners below can close over it directly.
  const [open, setOpen] = useState<Demo | null>(null);

  useEffect(() => {
    const made: HTMLElement[] = [];
    for (const demo of DEMOS) {
      const heading = document.getElementById(demo.chapter);
      if (!heading) continue;
      const btn = document.createElement("button");
      btn.className = "hb-demo-open";
      btn.type = "button";
      btn.innerHTML =
        '<svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">' +
        '<path d="M8 5v14l11-7z"></path></svg>';
      btn.append("Watch this work");
      btn.addEventListener("click", () => setOpen(demo));
      heading.insertAdjacentElement("afterend", btn);
      made.push(btn);
    }
    return () => made.forEach((el) => el.remove());
  }, []);

  // A demo takes over the screen; the page underneath must not scroll behind it.
  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prev;
    };
  }, [open]);

  return open ? <HandbookDemo demo={open} onClose={() => setOpen(null)} /> : null;
}
