"use client";

import { useEffect, useState } from "react";
import { DEMOS, type Demo } from "@/data/demos";
import HandbookDemo from "./HandbookDemo";

/** The one play glyph both the launcher and the contents marker use, so the
 *  two can never drift into different shapes. */
const PLAY = (size: number) =>
  `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">` +
  '<path d="M8 5v14l11-7z"></path></svg>';

/**
 * Puts a "Watch this work" button under every chapter heading that has a
 * demo, and a play marker beside that chapter's row in the contents.
 *
 * Done by reaching into the rendered Markdown rather than by putting the
 * button in the Markdown itself, because public/handbook.md is generated by
 * scripts/build-handbook.py from the same source as the printed book — and a
 * button is meaningless on paper. The heading ids it matches on are stable:
 * the build script writes them, and the contents page links to them.
 *
 * The buttons are built as plain DOM rather than portalled React nodes. That
 * looks like the lesser tool but it is the right one here: portals would need
 * the list of host elements in state, and filling that state from an effect is
 * a cascading render for something that never changes after the first paint.
 */
export default function DemoLauncher() {
  // setOpen from useState is stable for the life of the component, so the
  // listeners below can close over it directly.
  const [open, setOpen] = useState<Demo | null>(null);

  useEffect(() => {
    const made: HTMLElement[] = [];
    let marked = 0;
    for (const demo of DEMOS) {
      const heading = document.getElementById(demo.chapter);
      if (!heading) continue;
      const btn = document.createElement("button");
      btn.className = "hb-demo-open";
      btn.type = "button";
      btn.innerHTML = PLAY(13);
      btn.append("Watch this work");
      btn.addEventListener("click", () => setOpen(demo));
      heading.insertAdjacentElement("afterend", btn);
      made.push(btn);

      // The same fact, said where the reader is choosing what to read. Eleven
      // of fifty chapters have a demo and until now the contents said nothing
      // about which, so the only way to find one was to open chapters until a
      // button appeared.
      //
      // A marker, not a second launch button: the contents row is an <a>, and
      // a button inside a link is invalid and ambiguous to click. The row
      // still does what a contents row does — it goes to the chapter, where
      // the launcher is waiting.
      const row = document.querySelector(`a.bk-toc-chapter[href="#${demo.chapter}"]`);
      if (!row) continue;
      const mark = document.createElement("span");
      mark.className = "hb-toc-demo";
      mark.innerHTML = PLAY(9);
      mark.title = `Guided demo: ${demo.title}`;
      // Named for a screen reader, but with no text node of its own: the find
      // bar indexes every text node under .hb-body, and a visually-hidden
      // caption would give "demo" eleven hits in the contents that a reader
      // could never see highlighted.
      mark.setAttribute("role", "img");
      mark.setAttribute("aria-label", `${demo.title} has a guided demo`);
      row.append(mark);
      made.push(mark);
      marked++;
    }

    // An unexplained icon repeated eleven times is a puzzle, so the contents
    // says what it means — and only if something was actually marked.
    const toc = document.querySelector(".bk-toc");
    if (toc && marked) {
      const legend = document.createElement("p");
      legend.className = "hb-toc-legend";
      // The very marker being explained, same element and same class — a key
      // that does not match its map is worse than no key.
      legend.innerHTML = `<span class="hb-toc-demo" aria-hidden="true">${PLAY(9)}</span>`;
      legend.append(`${marked} of these chapters come with a guided demo you can watch.`);
      toc.append(legend);
      made.push(legend);
    }

    return () => made.forEach((el) => el.remove());
  }, []);

  // A demo takes over the screen; the page underneath must not scroll behind it.
  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prev;
    };
  }, [open]);

  return open ? <HandbookDemo demo={open} onClose={() => setOpen(null)} /> : null;
}
